# Generated by Django 4.0.5 on 2022-07-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Cargo',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Matricula',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Salario',
            new_name='salario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='Data_Nascimento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='Depto',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ES', 'Estagiário'), ('AS', 'Assistente'), ('JR', 'Júnior'), ('PL', 'Pleno'), ('SR', 'Sênior'), ('GR', 'Gerente')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
